version: "3.9"
services:
  app-service:
    image: "gymmy-app:dev"
    container_name: "gymmy-app_dev"
    build:
      context: app
      dockerfile: dev.Dockerfile
    networks:
      - gymmy-network
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=dev
    restart: "no"  # Could be always, on-failure, unless-stopped
  api-service:
    image: "gymmy-api:dev"
    container_name: "gymmy-api_dev"
    env_file: api/docker_envs/.env.development
    build:
      context: api
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - ./api:/app
    networks:
      - gymmy-network
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.8
    container_name: mongo
    restart: unless-stopped
    env_file: mongo/docker_envs/.env.development
    ports:
      - 27018:27017
    networks:
      - gymmy-network
    volumes:
      - ./mongo/:/docker-entrypoint-initdb.d/:ro
      # The named volume dbdata will persist the data stored in Mongo’s default data directory, /data/db.
      # This will ensure that you don’t lose data in cases where you stop or remove containers.
      - ./mongo/dbdata:/data/db
    command: [ --auth ]
networks:
  gymmy-network:
    name: gymmy-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
