exports.USERNAME_PARAM = 'username'
exports.EXERCISE_NAME_PARAM = 'exerciseName'
exports.LOCATION_PARAM = 'location'
exports.USER_CARDS_PARAM = 'cards'
exports.CARD_INDEX_PARAM = 'cardIndex'
exports.OBJECTIVE_PARAM = 'objective'